version: '3.9'
services:
 frontend-dumbplay:
   container_name: frontend-dumbplay
   image: ogak/dumbsound:1.1
   stdin_open: true
   ports:
     - 3000:3000
 backend-dumbplay:
   container_name: backend-dumbplay
   image: ogak/backendsound:1.3
   ports:
     - 5000:5000
